spring:
  application:
    name: shorten-url
  profiles:
    active: local

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:shortenUrl
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
service:
  url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/dev_db
    username: dev_user
    password: dev_pass

---

spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL:jdbc:mysql://prod-server:3306/prod_db}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}